[commands]
  dev  = "cargo run"
  test = "cargo test"

[pre_commands]
  dev  = "unset ARGV0"
  test = "unset ARGV0"

[aliases]
  NEXT_PUBLIC_API_KEY = "PUBLIC_API_KEY"
  VITE_ANON_KEY       = "ANON_KEY"

[[secrets_sources]]
  name              = "bitwarden"
  access_token_name = "BWS_ACCESS_TOKEN"

[[secrets_sources]]
  name              = "bitwarden"
  access_token_name = "BWS_ACCESS_TOKEN_2"
