name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  release:
    timeout-minutes: 20
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            targets: ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
            dependencies: |
              sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
          - os: macos-latest
            targets: ["x86_64-apple-darwin", "arm64-apple-darwin"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Rust setup
        uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3

      - name: Rust cache
        uses: swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
        with:
          shared-key: "release-${{ matrix.os }}"

      - name: Install dependencies
        if: matrix.dependencies != ''
        run: ${{ matrix.dependencies }}

      - name: Add targets
        run: |
          for target in ${{ join(matrix.targets, ' ') }}; do
            rustup target add $target
          done

      - name: Build targets
        run: |
          for target in ${{ join(matrix.targets, ' ') }}; do
            cargo build --release --target $target
          done

      - name: Prepare release artifacts
        run: |
          mkdir -p artifacts
          for target in ${{ join(matrix.targets, ' ') }}; do
            # Remove vendor names ('-apple' and '-unknown') from the target name
            target_name=$(echo $target | sed 's/-apple//; s/-unknown//')

            # Remove platform names ('-gnu', 'musl') from the target name
            target_name=$(echo $target_name | sed 's/-gnu//; s/-musl//')

            echo "target_name: $target_name"

            cp "target/$target/release/sm" "artifacts/secrets-machine-${target_name}"
          done

      - name: Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: artifacts/secrets-machine*

      - name: Clean up
        run: rm -rf artifacts
