name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 20
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-24.04
            targets: ["x86_64-unknown-linux-gnu"]
          - os: macos-latest
            targets: ["x86_64-apple-darwin"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4.2.2

      - name: Rust setup
        uses: dtolnay/rust-toolchain@1ff72ee08e3cb84d84adba594e0a297990fc1ed3

      - name: Rust cache
        uses: swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6
        with:
          shared-key: "test-${{ matrix.os }}"

      - name: Install Bitwarden CLI
        run: |
          curl https://bws.bitwarden.com/install | sh

      - name: Run tests
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
        run: cargo test -- --include-ignored

      - name: Run Compiled Tests
        env:
          BWS_ACCESS_TOKEN: ${{ secrets.BWS_ACCESS_TOKEN }}
        run: |
          chmod +x tests/compiled/test_all.sh
          chmod +x tests/compiled/eval_command.sh
          tests/compiled/test_all.sh "cargo run --"
